os: osx

language: swift

branches:
only:
- master

notifications:
 webhooks: https://fathomless-fjord-24024.herokuapp.com/notify


script:
- xcodebuild build -workspace Example/OVTimerLabel.xcworkspace -scheme OVTimerLabel-Example -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty;
